### ISSUE TITLE
devtools::build() deletes inst/doc

### ISSUE THREAD

**Issue by joehl** [r-lib/pkgbuild#70] opened 2019-03-14 17:42 UTC
Dear package authors,
I almost lost documents because devtools::build() deletes inst/doc.
Yes I know that devtools::build() in interactive mode warns me (Are you sure? Yes/No),
but no, if I say 'No' the build is interupted, and if I say 'Yes' I lose documents. Worse, in certain settings (triggering build in Rstudio) there is no warning but a silent deletion. I would expect devtools::build() to behave as R CMD build, which does not remove any sources it is packing into the build. 
Best regards
Jens Oehlschlägel

**Comment by jimhester** [comment] 2019-03-20 18:56
This is a duplicate of https://github.com/r-lib/pkgbuild/issues/62

**Closed by jimhester** 2019-03-20 18:56 UTC
