### ISSUE TITLE
`needs_compile` produces false positives

### ISSUE THREAD

**Issue by david-cortes** [r-lib/pkgbuild#130] opened 2022-01-26 02:58 UTC
From https://github.com/rstudio/rstudio/issues/9264

`pkgbuild::needs_compile()` oftentimes incorrectly decides that a package needs recompilation even though neither the compiled source code nor the `configure` file have changed, which is especially problematic when using the RStudio IDE to develop R packages.

A couple examples to try:
https://cran.r-project.org/web/packages/xgboost/index.html
https://cran.r-project.org/web/packages/MatrixExtra/index.html
https://cran.r-project.org/web/packages/rsparse/index.html

I am not 100% sure but I think:
* This issue is more likely to happen when having a custom `~/.R/Makevars` file with something like `PKG_CXXFLAGS += -O3`.
* I have not experienced this issue on Windows.
* This is especially more likely to happen after the command is run more than ~2mins or so since the last time the source was recompiled.

Can be checked for example by using the RStudio IDE button `Install and Restart` on some R package project after modifying some .R files without touching anything under `src/`.

**Comment by gaborcsardi** [comment] 2022-11-23 10:56
I can't reproduce this, I tried rsparse and MatrixExtra and get:
```r
> pkgbuild::needs_compile()
[1] FALSE
> system("touch R/*")
> pkgbuild::needs_compile()
[1] FALSE
```

I also tried modifying a `.R` source file instead of `touch`, and `pkgbuild::needs_compile()` still returns `FALSE`. 

It works correctly for `/src` as well:
```r
> pkgbuild::needs_compile()
[1] FALSE
> system("touch src/*.c*")
> pkgbuild::needs_compile()
[1] TRUE
```

**Comment by david-cortes** [comment] 2022-11-23 11:00
@gaborcsardi Does anything change if you set up a custom Makevars for your R user?

**Comment by gaborcsardi** [comment] 2022-11-23 11:08
A custom `Makevars` does not change anything, waiting a couple of minutes after the compilation does not change anything, either.

Do you use ccache or some other similar tool? What do you have in your `Makevars` file?

**Comment by david-cortes** [comment] 2022-11-23 11:11
I'm using the default `gcc` as it comes in debian. I don't think it includes `ccache` as the package doesn't show as installed in my system.

My Makevars file (`~/.R/Makevars`) is as follows:
```
CXXFLAGS += -O3 -march=native -fno-math-errno -fno-trapping-math
CXX11FLAGS += -O3 -march=native -fno-math-errno -fno-trapping-math
CXX14FLAGS += -O3 -march=native -fno-math-errno -fno-trapping-math
CXX17FLAGS += -O3 -march=native -fno-math-errno -fno-trapping-math
CXX20FLAGS += -O3 -march=native -fno-math-errno -fno-trapping-math
CFLAGS += -O3 -march=native -fno-math-errno -fno-trapping-math
FCFLAGS += -O3 -march=native -fno-math-errno -fno-trapping-math
FFLAGS += -O3 -march=native -fno-math-errno -fno-trapping-math
```

**Comment by gaborcsardi** [comment] 2022-11-23 11:12
Do you also see this from the command line or only from RStudio?

**Comment by david-cortes** [comment] 2022-11-23 11:13
I've never tried this from the command line. Do  you mean doing something like this?
```shell
R -e "pkgbuild::needs_compile()"
```

**Comment by gaborcsardi** [comment] 2022-11-23 11:28
Yeah, something like this in R:
```r
pkgload::load_all()
pkgbuild::need_compile()
pkgbuild::need_compile()
system("touch R/*.R")
pkgbuild::need_compile()
```

Btw. in RStudio Build -> Install does not use pkgbuild, and it runs 
```
R CMD INSTALL --preclean --no-multiarch --with-keep.source <pkg>
```
for me (whether I select the devtools tools or not), where `--preclean` will probably remove the object files, so yes, that will rebuild the package all the time, but this is independent of pkgbuild.

**Comment by david-cortes** [comment] 2022-11-23 11:36
I btw also experience the issue with the `Run Tests` RStudio button in files put under `tests/`, which as I understood from the linked issue at the top should call `pkgbuild::needs_compile()` internally, and the same with the button to build roxygen docs.

**Comment by gaborcsardi** [comment] 2022-11-23 11:48
I cannot reproduce it with `Run Tests`, either, on macOS, with a recent RStudio daily: 2022.11.0-daily+185. 

If you cannot reproduce it in a terminal, then it is potentially an RStudio issue. If you are able to update RStudio, then you could try a build from https://dailies.rstudio.com/

**Comment by gaborcsardi** [comment] 2022-11-27 09:32
I am going to close this because I cannot reproduce it, still. 

Please reopen it if you can reproduce it without RStudio or with a recent version of RStudio.

**Closed by gaborcsardi** 2022-11-27 09:32 UTC
Labels: bug, reprex
